# Generated by Django 6.0.8 on 2026-09-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
